name: Wake Up Render Server

on:
  schedule:
    # Runs at 6:55 AM WAT (which is 05:55 UTC)
    - cron: '55 5 * * *'
  workflow_dispatch: # Allows you to test it manually with a click

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the server
        run: curl -I -m 120 https://birthday-reminder-app-sq29.onrender.com/ping